### ISSUE TITLE
Resolve - Organism

### ISSUE THREAD

**Issue by tucotuco** [BiodiversityOntologies/bco#21]
BCO uses a class from CARO (single individual) while the DwC organism under discussion can be one or many organisms. Coordinate this with PCO.

**Comment by ramonawalls** [comment]
I imported "organismal entity" from PCO, and made dwc:Organism a subclass. I did not make it equivalent, because there is not restriction that pco:organismal entity be taxonomically homogeneous. @tucotuco, @robgur: does that work for you?

Also made dwc:Taxon a subclass of pco:collection of organisms.

We can later add logical restrictions to both of these to specify their taxonomic homogeneity.

**Comment by robgur** [comment]
Yes that works for me on both counts.

**Comment by tucotuco** [comment]
Those work for me too.
