### ISSUE TITLE
bco equivalancy of Event

### ISSUE THREAD

**Issue by ramonawalls** [BiodiversityOntologies/bco#55]
We currently specify dwc:Event equivalent to (bco:observing process or obi:specimen collecting process), because I think this is the context under which the dwc term was created. However, the text definition is "An action that occurs at some location during some time," which is much broader, and suggests equivalence with BFO:process.

**Comment by pbuttigieg** [comment]
Sounds right, but I think a comment explaining the "usual " meaning would
be well-placed.

**Comment by tucotuco** [comment]
The definition was indeed meant to be broad from the outset so that it
might correspond with something more generic than the use cases we cover
within our domain. In fact, it had its origin in dc:Event, though from that
definition you can see why we had to create a distinct one:

"A non-persistent, time-based occurrence."

From http://dublincore.org/documents/dcmi-terms/#dcmitype-Event

**Comment by ramonawalls** [comment]
I am changing this to be equivalent to bfo:process, based on @tucotuco 's suggestion above. I will remove the occurs in some site axiom.
